### ISSUE TITLE
Checking that way works but what about having to change your grid to a 5X5?

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/Slot-Machine#1]
https://github.com/Selemabala/Slot-Machine/blob/69153c803602037d49d70f7231fe2a51da0f98ca/Slot%20Machine/Program.cs#L46

In case the grid changes from 3X3 to 5X5 then you have to add more cases here. We suggest to use a for loop and an indexer to do the same checks without having to write each one of them

**Comment by Selemabala** [comment]
I corrected this to the other option of grid actual size
