### ISSUE TITLE
This will throw and exception if the user does not provide numbers

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/Slot-Machine#10]
https://github.com/Selemabala/Slot-Machine/blob/504aaa7ea8944aaa048f08b9d564f5604c0f6648/Slot%20Machine/Program.cs#L47
Unhandled exception. System.FormatException: The input string 'X' was not in a correct format.

You should add validations fro numbers only

**Comment by Selemabala** [comment]
Validation code successfully added
