### ISSUE TITLE
Is this variable needed?

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/Slot-Machine#11]
https://github.com/Selemabala/Slot-Machine/blob/504aaa7ea8944aaa048f08b9d564f5604c0f6648/Slot%20Machine/Program.cs#L81

You assign the value of the constant SECOND_GRID_VALUE to this variable and you are using it only to check if the outerloop==winningLine 18 lines later. 

There's no reason to have this variable, you can just use your constant.

**Comment by Selemabala** [comment]
Variable removed
