### ISSUE TITLE
This won't work if the gird changes.

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/Slot-Machine#6]
https://github.com/Selemabala/Slot-Machine/blob/9d14fb2c04b1107745cc4cecaed68eb3249e863b/Slot%20Machine/Program.cs#L113-L130

Stop using constants to just select the grid places that you want. Let the for loop do that. For example for a diagonal the trick would be to check the grid place that has outerloop and innerloop the same (0,0 1,1,2,2 etc).

Using the loop's indexers the solution will work if the grid changes from 3X3 to 5X5

**Comment by Selemabala** [comment]
You were right, I made proper changes
