### ISSUE TITLE
check your constant names. 

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/Slot-Machine#7]
https://github.com/Selemabala/Slot-Machine/blob/72fe774cdb43c03122e0d63c0018dea646ab79e2/Slot%20Machine/Program.cs#L11-L30

Constant names should be informative enough so that the code reader will be able to understand the constant without checking the code

Also, names that have 2 parts should be separated with _  (GRID_COLUMNS instead of GRIDCOLUMN)

**Comment by Selemabala** [comment]
changes  made to more understandable ones
