### ISSUE TITLE
Very bad naming

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/Slot-Machine#8]
https://github.com/Selemabala/Slot-Machine/blob/707261540b519babde25f441caffce8931fb021d/Slot%20Machine/Program.cs#L156

I was trying to read your code to understand it and I kept trying to remember what this variable was due to the bad name. This is just the first item of the grid not diagonal values.

The point of having a good variable name is that you don;t need to check what's assigned to it each time you see it. A name like 

firstGridElement or something similar gives you this piece of info right away. 

Same applies to a lot of variables in your code. Check again for variable names.

**Comment by Selemabala** [comment]
Sorry, I did make changes in naming

**Comment by AlexKap23** [comment]
There are still some spots here and there. 

int firstGridElement = grid.GetLength(0); -> this is not the first grid element, it's the length of the grid in rows.
