### ISSUE TITLE
WIN is a constant but your grid can change

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/Slot-Machine#9]
https://github.com/Selemabala/Slot-Machine/blob/3d3cf6d1d210dd6f833eeae243e9610f491a3633/Slot%20Machine/Program.cs#L98

This constant is used so that your program can find out if there's a win on All horizontals or not. And you are doing that by incrementing a counter each time you find a win. BUT if your grid size is a 3X3 and your second loop starts counting from 1 then only 2 wins are going to be counted. So it doesn't matter if you win or loose( you have 3 symbols being the same or 2 being the same) the program always displays that you are loosing.

I suggest that this WIN should be calculated based on the size of the grid. Because if the grid size changes to 5X5 this win should be changed to 4. Calculating that based on the grid's size will do the trick.

**Comment by Selemabala** [comment]
Wiining has been changed and now is calculated in according the values of the grid
